version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: kosenctfx
      MYSQL_USER: kosenctfxuser
      MYSQL_PASSWORD: kosenctfxpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 13306:3306

    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-query.log

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - 9000:8080

  minio:
    image: minio/minio
    ports:
      - "49000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: ["server", "/data"]

  kosenctfx:
    build:
      context: .
    environment:
      DBDSN: 'kosenctfxuser:kosenctfxpassword@tcp(db:3306)/kosenctfx'
      REDIS: "redis:6379"
      FRONT: 'http://front.web.localhost:8080'
      MAIL: 'kosenctf@example.com'
      MAIL_SERVER: 'smtp.gmail.com:587'
      MAIL_PASSWORD: 'XXXXXXXXXXXX'
    ports:
      - 5000:5000
    command: ["sh", "-c" ,"sleep 10 && ./scoreserver"]
    depends_on:
      - db
      - redis
      - minio

  front:
    build:
      context: ./ui
    ports:
      - 8080:80
