version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: kosenctfx
      MYSQL_USER: kosenctfxuser
      MYSQL_PASSWORD: kosenctfxpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-query.log
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql

  redis:
    image: redis:6
    volumes:
      - ./redis/data:/data

  scoreserver:
    build:
      context: scoreserver
    environment:
      DBDSN: 'kosenctfxuser:kosenctfxpassword@tcp(db:3306)/kosenctfx'
      REDIS: 'redis://redis:6379'
      FRONT: 'http://localhost:1/'
      MAIL: 'kosenctf@example.com'
      MAIL_SERVER: 'smtp.gmail.com:587'
      MAIL_PASSWORD: 'XXXXXXXXXXXXXXXXXX'
      ADMIN_WEBHOOK: ''
      SOLVE_WEBHOOK: ''
      TASK_OPEN_WEBHOOK: ''
      BUCKET_ENDPOINT: "minio:9000"
      BUCKET_REGION: "us-east-1"
      BUCKET_ACCESS_KEY: "minio"
      BUCKET_SECRET_KEY: "minio123"
      BUCKET_NAME: "kosenctfx-challenges"
      BUCKET_INSECURE: "1"
      ADMIN_TOKEN: "admin"
    ports:
      - "5000:5000"
  
  ui:
    build:
      context: ui
      dockerfile: Dockerfile.prod
    environment:
      SSR_API_HOST: "http://nginx:80/api/"
    command: |
      bash -c 'sleep 15; yarn build && yarn start'
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    ports:
      - "8000:80"

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: ["server", "/data"]
    ports:
      - "9000:9000"  # minio

