version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: kosenctfx
      MYSQL_USER: kosenctfxuser
      MYSQL_PASSWORD: kosenctfxpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 13306:3306

    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-query.log

  adminer:
    image: adminer
    ports:
      - 9000:8080

  minio:
    image: minio/minio
    ports:
      - "49000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: ["server", "/data"]
