global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: "kosenctfx metrics"
    metrics_path: /api/admin/metrics
    basic_auth:
      username: "admin"
      password: "admin"
    static_configs:
      - targets:
        - nginx:80

